In [13]:
import os
import numpy as np  
import matplotlib.pyplot as mtp  
import pandas as pd  

In [14]:
data=pd.read_csv('/Users/watchara.p/Desktop/Gene_UPDEG_ML.csv',low_memory=False)
data.head()

Genes  ACE2    ALKBH8    AMOTL1      ANK2    ARID5A     ASB17  ASH2L  \
0      0   0.0  8.386579  7.287812  7.731897  7.368372  7.284393    0.0   
1      0   0.0  0.000000  0.000000  8.511641  0.000000  0.000000    0.0   
2      0   0.0  0.000000  0.000000  7.600124  0.000000  0.000000    0.0   
3      0   0.0  0.000000  0.000000  7.779532  0.000000  0.000000    0.0   
4      0   0.0  0.000000  0.000000  8.534909  0.000000  0.000000    0.0   

       ASZ1      ATRX  ...   TWISTNB     UBAC2    UBTFL1  UNC13A      VARS  \
0  8.205363  15.73572  ...  6.943974  8.694908  14.47735     0.0  6.958369   
1  8.778321  15.85638  ...  6.122663  0.000000  14.48805     0.0  0.000000   
2  8.217196  15.92986  ...  6.036867  0.000000   0.00000     0.0  0.000000   
3  9.049714   0.00000  ...  6.474401  0.000000   0.00000     0.0  0.000000   
4  8.489758   0.00000  ...  7.170546  0.000000   0.00000     0.0  0.000000   

      WDR34   ZCCHC24     ZFP42    ZNF234    ZNF608  
0  7.934554  7.278980  15.92713  12.00545  6.813715  
1  0.000000  7.631227  16.02296  12.18443  6.558315  
2  0.000000  7.203963   0.00000  12.49294  6.657884  
3  0.000000  7.756562   0.00000   0.00000  0.000000  
4  0.000000  7.699783   0.00000   0.00000  0.000000  

[5 rows x 172 columns]

In [15]:
x=data.iloc[:,1 :171]
y=data.iloc[:,0]

x
y

0     0
1     0
2     0
3     0
4     0
     ..
85    1
86    1
87    1
88    1
89    1
Name: Genes, Length: 90, dtype: int64

In [16]:
from sklearn.preprocessing import StandardScaler ,LabelEncoder


scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_scaled = pd.DataFrame(x_scaled, columns=x.columns)
x_scaled.head()

ACE2    ALKBH8    AMOTL1      ANK2    ARID5A     ASB17     ASH2L  \
0 -0.515201  1.089754  0.710475  0.518007  0.728325  0.594013 -0.372478   
1 -0.515201 -0.440277 -0.581321  0.641747 -0.520842 -0.583988 -0.372478   
2 -0.515201 -0.440277 -0.581321  0.497096 -0.520842 -0.583988 -0.372478   
3 -0.515201 -0.440277 -0.581321  0.525566 -0.520842 -0.583988 -0.372478   
4 -0.515201 -0.440277 -0.581321  0.645440 -0.520842 -0.583988 -0.372478   

       ASZ1      ATRX     BAHD1  ...       TTN   TWISTNB     UBAC2    UBTFL1  \
0  1.079314  1.230101  1.184819  ...  0.572354  0.516912  0.980553  2.286427   
1  1.194179  1.245646  0.937470  ... -0.653418  0.378849 -0.564246  2.288434   
2  1.081686  1.255113 -0.529142  ... -0.653418  0.364427 -0.564246 -0.428941   
3  1.248588 -0.797197 -0.529142  ... -0.653418  0.437976 -0.564246 -0.428941   
4  1.136329 -0.797197 -0.529142  ... -0.653418  0.554999 -0.564246 -0.428941   

     UNC13A      VARS     WDR34   ZCCHC24     ZFP42    ZNF234  
0 -0.266343  0.886951  1.154492  0.570002  1.922749  1.721796  
1 -0.266343 -0.459615 -0.478538  0.626359  1.937430  1.754370  
2 -0.266343 -0.459615 -0.478538  0.558000 -0.517245  1.810518  
3 -0.266343 -0.459615 -0.478538  0.646412 -0.517245 -0.463163  
4 -0.266343 -0.459615 -0.478538  0.637328 -0.517245 -0.463163  

[5 rows x 170 columns]

In [17]:
numbers = range(len(x_scaled))
groups = [f"Group {num // 3 + 1}" for num in numbers]
groups

['Group 1',
 'Group 1',
 'Group 1',
 'Group 2',
 'Group 2',
 'Group 2',
 'Group 3',
 'Group 3',
 'Group 3',
 'Group 4',
 'Group 4',
 'Group 4',
 'Group 5',
 'Group 5',
 'Group 5',
 'Group 6',
 'Group 6',
 'Group 6',
 'Group 7',
 'Group 7',
 'Group 7',
 'Group 8',
 'Group 8',
 'Group 8',
 'Group 9',
 'Group 9',
 'Group 9',
 'Group 10',
 'Group 10',
 'Group 10',
 'Group 11',
 'Group 11',
 'Group 11',
 'Group 12',
 'Group 12',
 'Group 12',
 'Group 13',
 'Group 13',
 'Group 13',
 'Group 14',
 'Group 14',
 'Group 14',
 'Group 15',
 'Group 15',
 'Group 15',
 'Group 16',
 'Group 16',
 'Group 16',
 'Group 17',
 'Group 17',
 'Group 17',
 'Group 18',
 'Group 18',
 'Group 18',
 'Group 19',
 'Group 19',
 'Group 19',
 'Group 20',
 'Group 20',
 'Group 20',
 'Group 21',
 'Group 21',
 'Group 21',
 'Group 22',
 'Group 22',
 'Group 22',
 'Group 23',
 'Group 23',
 'Group 23',
 'Group 24',
 'Group 24',
 'Group 24',
 'Group 25',
 'Group 25',
 'Group 25',
 'Group 26',
 'Group 26',
 'Group 26',
 'Group 27',


In [29]:
from sklearn.metrics import confusion_matrix, precision_score, f1_score
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
import numpy as np

# Assuming x_scaled and y are your features and labels, and `groups` is defined for LOGO
kf = LeaveOneGroupOut()

model_rf = RandomForestClassifier(random_state=99)
model_sv = SVC(kernel='linear', probability=True, random_state=99)
model_lr = LogisticRegression(random_state=99)
model_gbc = GradientBoostingClassifier(random_state=99)

# Lists to store aggregated true and predicted labels for all models
y_true_all = []
y_pred_rf_all = []
y_pred_sv_all = []
y_pred_lr_all = []
y_pred_gbc_all = []


# Performance metrics lists
acc_rf, acc_sv, acc_gbc, acc_lr = [], [], [], []
pre_rf, pre_sv, pre_gbc, pre_lr = [], [], [], []
sens_rf, sens_sv, sens_gbc, sens_lr = [], [], [], []
spec_rf, spec_sv, spec_gbc, spec_lr = [], [], [], []
f11_rf, f11_sv, f11_gbc, f11_lr = [], [], [], []


In [30]:
# LOGO loop
for train_index, test_index in kf.split(x_scaled, groups=groups):
    X_train, X_test = x_scaled.iloc[train_index], x_scaled.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Fit the models
    model_gbc.fit(X_train, y_train)
    model_sv.fit(X_train, y_train)
    model_rf.fit(X_train, y_train)
    model_lr.fit(X_train, y_train)

    # Predict
    y_pred_lr = model_lr.predict(X_test)
    y_pred_sv = model_sv.predict(X_test)
    y_pred_rf = model_rf.predict(X_test)
    y_pred_gbc = model_gbc.predict(X_test)

    # Store true and predicted labels for aggregation
    y_true_all.extend(y_test)  # Add true labels
    y_pred_lr_all.extend(y_pred_lr)
    y_pred_sv_all.extend(y_pred_sv)
    y_pred_rf_all.extend(y_pred_rf)
    y_pred_gbc_all.extend(y_pred_gbc)


# Aggregated confusion matrix and metrics
y_true_all = np.array(y_true_all)
y_pred_rf_all = np.array(y_pred_rf_all)
y_pred_sv_all = np.array(y_pred_sv_all)
y_pred_lr_all = np.array(y_pred_lr_all)
y_pred_gbc_all = np.array(y_pred_gbc_all)

cm_rf_total = confusion_matrix(y_true_all, y_pred_rf_all, labels=labels)
cm_sv_total = confusion_matrix(y_true_all, y_pred_sv_all, labels=labels)
cm_lr_total = confusion_matrix(y_true_all, y_pred_lr_all, labels=labels)
cm_gbc_total = confusion_matrix(y_true_all, y_pred_gbc_all, labels=labels)

print("Aggregated Confusion Matrix (RF):\n", cm_rf_total)
print("Aggregated Confusion Matrix (GBC):\n", cm_gbc_total)
print("Aggregated Confusion Matrix (LR):\n", cm_lr_total)
print("Aggregated Confusion Matrix (SVM):\n", cm_sv_total)

Aggregated Confusion Matrix (RF):
 [[47  1]
 [ 2 40]]
Aggregated Confusion Matrix (GBC):
 [[41  7]
 [17 25]]
Aggregated Confusion Matrix (LR):
 [[46  2]
 [ 5 37]]
Aggregated Confusion Matrix (SVM):
 [[46  2]
 [ 5 37]]
